# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d40c2ae0afed3eaf9643a20320ae23f68c3167154878357a910dc4e8414099da57792456e188a65453001d9c1b959b92d8fcc89989b280fe1c72ec6cf8d14b5e

test:
  secret_key_base: 09b1dba1f167f35f42484ae1b7f65b11022edc2f9339a6d650f07870df7479631d3b29e8278d3ed9a4d30ddd2aa6875037e327c764e4ef8f3207ae22129c9b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
